### PR TITLE
Release v2.10.5

### PR DESCRIPTION
**Pull request by NumminorihSF**
GitHub repo has updated dependencies but there were not any npm release. As v2.10.4 is already released so it looks like release should have v2.10.5

### CODE REVIEW

**Comment by MauriceYipYip** [comment]
@zazaian @paulmillr

**Comment by nietaki** [comment]
@zazaian @shvaikalesh  Can you please release the new version? The version of `node-sass` referenced in the last released version of `sass-brunch` is from mid-2016 and doesn't support Node 8 (as opposed to the version on current master).

Also, according to this comment, the release was planned last month: https://github.com/brunch/sass-brunch/pull/131#issuecomment-269315933

**Comment by zazaian** [comment]
@MauriceYipYip @shvaikalesh I'm afraid I'm not one of the maintainers of `sass-brunch`. That honor seems likely to go to @paulmillr and @es128. Can we have a pow-wow about this? This feels like a crucial library for the elixir/Phoenix communities and I could see developers (including myself) having a hard time using current Node versions without issue.

**Comment by zazaian** [comment]
@nietaki @MauriceYipYip sorry for the delayed response here, just got to Berlin and it's been hectic settling in over here.

**Comment by MauriceYipYip** [comment]
@zazaian the only thing that needs to be done is tag the latest master with 2.10.5. So we can import it as dependency from https://www.npmjs.com/package/sass-brunch

**Comment by zazaian** [comment]
@MauriceYipYip I just looked at this and was literally just about to make that same comment. @paulmillr @es128 please issue a 2.10.5 release for commit 2d47094d8c259f07030a99433bc935d1ab753914. This tag has updates and should be compatible with newer versions of nodejs.

@MauriceYipYip in the meantime please feel free to use my `zazaian/sass-brunch` fork as apparently I've been using this for several months without issue. I can issue a 2.10.5 release in the meantime on my fork as a stepping stone for anyone waiting for the 2.10.5 release on the primary repo.

**Comment by zazaian** [comment]
@MauriceYipYip @shvaikalesh @nietaki I've just issued a new release on my fork for the newest changes. Please find that release here: https://github.com/zazaian/sass-brunch/releases/tag/2.10.5

Hopefully this will just serve as a stepping stone for the time being until a new release is issued on the brunch/sass-brunch repo.

**Comment by sickill** [comment]
@zazaian I tried your fork on Node 6, and while it installed fine, running `brunch build` didn't write any files (although with `--debug` flag it lies that it's writing them). Do I need Node 7 or 8?

**Comment by zazaian** [comment]
Hey @sickill - I haven't tested this with Node 6 at all. It was originally built on Node 7, was used with 8 and now is current on 9.8.0 and is working fine. Let me know if any of the newer node versions work for you and I'll try to assist otherwise.

**Comment by sickill** [comment]
@zazaian so it doesn't work for me on Node 8 either. I have made a repo with all the files to reproduce the problem: 

1. `git clone https://github.com/sickill/brunch-issue`
2. `cd brunch-issue`
3. `npm install`
4. `node_modules/brunch/bin/brunch build -d` - note how it says it's writing the files here

But no files are written in `here` directory.

**Comment by zazaian** [comment]
Hey @sickill - I wonder if it's an issue with your package.json config.
I'll take a look at it when I get to my computer later and let you know if
I can assist at all.

Just out of curiosity are you using this in conjunction with any backend
platforms or is this for a full JS app?

**Comment by sickill** [comment]
@zazaian I use it within my [Phoenix](http://phoenixframework.org/) app, but extracted the assets folder from it into the separate linked repo, where the same problem happens.

**Comment by zazaian** [comment]
@sickill - got it. I'll take a look and see what I can do.

FYI Phoenix is moving to Webpack by default as of 1.4.0, so this may be a
moot point. I'd already migrated a phoenix 1.3 app to webpack successfully
before the Phoenix team announced it, just because maintaining all of these
brunch libs has been challenging.

**Comment by sickill** [comment]
@zazaian aha! Migrating to webpack crossed my mind when trying to troubleshoot this brunch problem without success, but didn't know it at all, and I assumed brunch will be default in Phoenix in the future. Thanks for mentioning this. Do you have some example of how you set it up in Phoenix app?

**Comment by zazaian** [comment]
@sickill that branch is on a private repo but I'll see if I can extract
some steps. I'll probably do a writeup on this sooner than later.

There are a couple of articles about the topic, though the best I've found
is a thread in the phoenix github repo discussing these changes. There are
some comments by @gazler that spell out well what they did to swap out
brunch with webpack in phoenix itself.

Either way I'll see if I can help you get your Brunch issues sorted here.

**Comment by sickill** [comment]
@zazaian thanks. I'll read the discussion in phoenix repo. Given this, it's not that important to me anymore to fix the brunch setup, so don't spend too much time on it! Thanks so much.

**Comment by zazaian** [comment]
Hey @sickill my pleasure, let me know if you find any good stuff about
doing the upgrade as I'm upgrading another app to phoenix 1.4 soon.

**Comment by sickill** [comment]
@zazaian I thought Phoenix generator is probably doing a good job at integrating webpack into Phoenix so I generated new app with 1.3 generator and then with current dev generator, and made a diff: https://github.com/sickill/phoenix-1.3-to-dev/commit/fa4e9d082149db42b6acc03c3cd077024a4185db I'll start from here :)

**Comment by paulmillr** [comment]
v2.10.5 is out.

**Pull request closed without merging**
