### PR TITLE
Remove built in support of css modules in favor of postcss-brunch

### PR DESCRIPTION
**Pull request by kuon**
With https://github.com/brunch/postcss-brunch/pull/33

should fix https://github.com/brunch/sass-brunch/issues/124

Even if not absolutely required for it to work, I think it is good to drop this code.

I made some tests with `postcss-brunch` and `sass-brunch` and everything works (modules and autoprefixer).

I think a test suite that test `sass-brunch` with `postcss-brunch` and a few processors should live somewhere. I don't know in what repo to put it as neither are absolutely dependent on the other.

I bumped the version because this might break backward compatibility.

### CODE REVIEW

**Comment by bdavidxyz** [comment]
Excellent. Thanks. Can't wait for the PR to be merged.

**Comment by paulmillr** [comment]
Don't bump the version. Keep it 2.9.0. Just mention in the readme that users would need to downgrade to 2.6.

**Comment by kuon** [comment]
I changed my commit to bump only to 2.9.0

**Comment by paulmillr** [comment]
Thanks!

**Comment by kuon** [comment]
But before merging this, I need to find a solution for https://github.com/brunch/postcss-brunch/pull/33 first

**Pull request closed without merging**
