### PR TITLE
Update version to 2.10.8

### PR DESCRIPTION
**Pull request by dlepaux**

### CODE REVIEW

**Comment by dlepaux** [comment]
@paulmillr Hello !
Here the PR with the package.json update version etc
Thank you in advance

**Comment by paulmillr** [comment]
https://github.com/brunch/brunch.github.io/issues/290

this issue happened because of the code in master

we can't release it like this @dlepaux

**Comment by dlepaux** [comment]
Ok ! What is necessary to do to update ?? I can pass time to fix that ! Could you just tell me what to do !? Thank you @paulmillr

**Comment by shvaikalesh** [comment]
@dlepaux To release, we need to make sure that at least Brunch website builds OK. With current `master`, and probably this PR, it doesn't. Super simple imports [like this one](https://github.com/brunch/brunch.github.io/blob/source/app/app.scss#L1) do not work. It might be `node-sass` version, or `getDependencies`, or `progeny` or whatever.

**Comment by dlepaux** [comment]
Hello @shvaikalesh, I've just update my PR, I've use the original glob importer and the brunch website build works very well !
So for me it's done now.
Waiting your return about it !
Thank you

**Comment by shvaikalesh** [comment]
@paulmillr It is safe to release now.

**Comment by paulmillr** [comment]
@dlepaux thank you

**Pull request merged**
