### PR TITLE
Feature/native mode globbing

### PR DESCRIPTION
**Pull request by nathamanath**
glob imports when in native mode

### CODE REVIEW

**Comment by shvaikalesh** [comment]
Please, rebase. LGTM otherwise.

**Comment by denysdovhan** [comment]
@shvaikalesh let me include these commits in my PR #145. What do you think?

**Comment by shvaikalesh** [comment]
@denysdovhan Sure

**Comment by nathamanath** [comment]
rebased :)

**Comment by denysdovhan** [comment]
@nathamanath wait for a while. I'm gonna merge your PR with mine.

**Comment by denysdovhan** [comment]
Merged with #145.

**Pull request closed without merging**
